// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE7bvD6a278zMi8T34tg2Mjbxb1SZmpfg',
    appId: '1:617853047944:web:050fd419574b9095c3fb3d',
    messagingSenderId: '617853047944',
    projectId: 'mhmart-c4852',
    authDomain: 'mhmart-c4852.firebaseapp.com',
    storageBucket: 'mhmart-c4852.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCSLJnU-JuP0GyMs5A5E-5Ic9YxPZF8k',
    appId: '1:617853047944:android:66cdf861ebb17f22c3fb3d',
    messagingSenderId: '617853047944',
    projectId: 'mhmart-c4852',
    storageBucket: 'mhmart-c4852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkGdMM9Q1yK3fdzGAwVRM2Z-YjTvaBDc',
    appId: '1:617853047944:ios:3b706eedc9618be4c3fb3d',
    messagingSenderId: '617853047944',
    projectId: 'mhmart-c4852',
    storageBucket: 'mhmart-c4852.firebasestorage.app',
    iosBundleId: 'com.example.mhmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQkGdMM9Q1yK3fdzGAwVRM2Z-YjTvaBDc',
    appId: '1:617853047944:ios:3b706eedc9618be4c3fb3d',
    messagingSenderId: '617853047944',
    projectId: 'mhmart-c4852',
    storageBucket: 'mhmart-c4852.firebasestorage.app',
    iosBundleId: 'com.example.mhmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE7bvD6a278zMi8T34tg2Mjbxb1SZmpfg',
    appId: '1:617853047944:web:2cecc3d0257b2e51c3fb3d',
    messagingSenderId: '617853047944',
    projectId: 'mhmart-c4852',
    authDomain: 'mhmart-c4852.firebaseapp.com',
    storageBucket: 'mhmart-c4852.firebasestorage.app',
  );
}
